from dataclasses import dataclass, field


@dataclass
class RolloutResult:
    """
    Output structure of the rollout engine
    """

    task_id: str
    prompt_token_ids: list[int]
    response_token_ids: list[int]
    logprobs: list[float]
    text: str
    loss_mask: list[int] = field(default_factory=list)
    step_spans: list[tuple[int, int]] = field(default_factory=list)
    judge_score: float | None = None

@dataclass
class Trajectory:
    
    task_id: str
    prompt_token_ids: list[int]
    response_token_ids: list[int]
    rollout_logprobs: list[float]
    policy_version: int
    hint_free: str = ""
    hint_bearing: str = ""
    # Judge score, attached opportunistically for diagnostics. Never used in the loss, and
    # never gates whether a trajectory is trained on: the blog's headline finding is that
    # G=1 with failures RETAINED is the most efficient configuration.
    judge_score: float | None = None

    # where (start, end) of the steps, demarcated by the tuple and used to index into the response_token_ids
    step_spans: list[tuple[int, int]] = field(default_factory=list)
    
    # 1 for tokens generated by the model, 0 on tokens the environment injected via tool calls
    loss_mask: list[int] = field(default_factory=list)

    def __post_init__(self) -> None:
        if len(self.response_token_ids) != len(self.rollout_logprobs):
            raise ValueError(
                f"task {self.task_id}: {len(self.response_token_ids)} response tokens but "
                f"{len(self.rollout_logprobs)} rollout logprobs -- these must align 1:1"
            )
        if self.loss_mask and len(self.loss_mask) != len(self.response_token_ids):
            raise ValueError(
                f"task {self.task_id}: loss_mask length {len(self.loss_mask)} != "
                f"{len(self.response_token_ids)} response tokens"
            )

    def staleness(self, current_version: int) -> int:
        # check staleness of the data, used to prune the rollout buffer
        return current_version - self.policy_version 