from __future__ import annotations

import asyncio
from collections import Counter, deque
from dataclasses import dataclass, field


@dataclass
class Trajectory:
    
    task_id: str
    prompt_token_ids: list[int]
    response_token_ids: list[int]
    rollout_logprobs: list[float]
    policy_version: int
    hint: str = ""
    # Judge score, attached opportunistically for diagnostics. Never used in the loss, and
    # never gates whether a trajectory is trained on: the blog's headline finding is that
    # G=1 with failures RETAINED is the most efficient configuration.
    judge_score: float | None = None

    # where (start, end) of the steps, demarcated by the tuple and used to index into the response_token_ids
    step_spans: list[tuple[int, int]] = field(default_factory=list)
    
    # 1 for tokens generated by the model, 0 on tokens the environment injected via tool calls
    loss_mask: list[int] = field(default_factory=list)

    def __post_init__(self) -> None:
        if len(self.response_token_ids) != len(self.rollout_logprobs):
            raise ValueError(
                f"task {self.task_id}: {len(self.response_token_ids)} response tokens but "
                f"{len(self.rollout_logprobs)} rollout logprobs -- these must align 1:1"
            )

    def staleness(self, current_version: int) -> int:
        return current_version - self.policy_version


@dataclass
class StoreStats:

    added: int = 0
    sampled: int = 0
    evicted_stale: int = 0
    evicted_capacity: int = 0
    staleness_histogram: Counter[int] = field(default_factory=Counter)

    def as_metrics(self) -> dict[str, float]:
        total = sum(self.staleness_histogram.values())
        mean_staleness = (
            sum(k * v for k, v in self.staleness_histogram.items()) / total if total else 0.0
        )
        return {
            "store_added": float(self.added),
            "store_sampled": float(self.sampled),
            "store_evicted_stale": float(self.evicted_stale),
            "store_evicted_capacity": float(self.evicted_capacity),
            "store_mean_staleness": mean_staleness,
            "store_max_staleness_seen": float(max(self.staleness_histogram, default=0)),
        }


class TrajectoryStore:
    """Async-safe FIFO store with staleness-bounded sampling.

    Rollout workers call `add()`; the trainer calls `sample()`. Both take the same lock, so
    the store is safe for many concurrent producers and one consumer.
    """

    def __init__(self, capacity: int = 512, max_staleness: int = 3) -> None:
        self.capacity = capacity
        self.max_staleness = max_staleness
        self.policy_version = 0
        self._buffer: deque[Trajectory] = deque()
        self._not_empty = asyncio.Condition()
        self.stats = StoreStats()

        # tracking the rollout policy
        self._version_generation = 0

    async def add(self, trajectory: Trajectory) -> None:
        # Add a finished trajectory, use a FIFO system, oldest gets evicted
        async with self._not_empty:
            while len(self._buffer) >= self.capacity:
                self._buffer.popleft() # get rid of the oldest trajectory
                self.stats.evicted_capacity += 1
            self._buffer.append(trajectory)
            self.stats.added += 1
            self._not_empty.notify_all() # anything waiting gets alerted of new trajectories! 

    def ready(self, batch_size:int) -> bool:
        # do I have enough to make a batch? 
        num_ready_samples = sum(1 for t in self._buffer if t.staleness(self.policy_version) <= self.max_staleness)
        if num_ready_samples >= batch_size: 
            return True
        else: 
            return False

    async def sample(self, batch_size: int, drop_stale: bool = True, timeout:float=0.0) -> list[Trajectory]:
        # wait until we have batch_size in our rollout buffer
        async with self._not_empty:
            # lets start making the batch
            batch: list[Trajectory] = []
            while self._buffer and len(batch) < batch_size:
                if timeout > 0: 
                    try: 
                        async with asyncio.timeout(timeout):
                            await self._not_empty.wait_for(
                                lambda: self.ready(batch_size)
                            )
                    except TimeoutError:
                        pass
                trajectory = self._buffer.popleft()
                staleness = trajectory.staleness(self.policy_version)
                if drop_stale and staleness > self.max_staleness:
                    self.stats.evicted_stale += 1
                    continue
                self.stats.staleness_histogram[staleness] += 1
                batch.append(trajectory)
            self.stats.sampled += len(batch)
            return batch

    async def set_policy_version(self, version: int) -> None:
        """Bump the policy version after a weight sync. Existing trajectories get staler"""
        async with self._not_empty:
            self.policy_version = version
            self._version_generation += 1
            # Waiters may now be unsatisfiable (everything went stale) -- wake them so they
            # re-evaluate rather than hanging until timeout.
            self._not_empty.notify_all()

    async def prune_stale(self) -> int:
        # prunes stale entries - done every weight_sync
        async with self._not_empty:
            keep = [
                t for t in self._buffer if t.staleness(self.policy_version) <= self.max_staleness
            ]
            removed = len(self._buffer) - len(keep)
            self._buffer = deque(keep)
            self.stats.evicted_stale += removed
            return removed

    def __len__(self) -> int:
        return len(self._buffer)

    def metrics(self) -> dict[str, float]:
        """Store metrics for the trainer log.

        Watch `store_evicted_stale` and `store_mean_staleness`: a large stale-eviction
        fraction means rollout is too slow relative to the treainer, and the fix is to
        rebalance the GPU split (more rollout workers) rather than to raise the bound.
        """
        metrics = self.stats.as_metrics()
        metrics["store_size"] = float(len(self._buffer))
        metrics["store_policy_version"] = float(self.policy_version)
        return metrics
