from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from collections import defaultdict

import torch
import torch.distributed as dist
from torch.distributed.checkpoint.state_dict import (
    StateDictOptions,
    get_state_dict,
    set_state_dict,
)
from torch.distributed.fsdp import FSDPModule
from torch.distributed.tensor import DTensor
from torch.utils.data import Dataset
from torchdata.stateful_dataloader import StatefulDataLoader

from typing import Iterable, List, Optional, Set

from train.config import Config
from data.dataset import HINT_SEPARATOR, Task
from train.backends.backend import WeightBucket, WeightTransport
from train.loss import EMAAdvantageClipper, masked_mean, sdpo_loss
from train.store import TrajectoryStore

from train.utils import build_batch, SDPOBatch, response_logprobs_from_hidden

logger = logging.getLogger(__name__)


@dataclass
class _RolloutStat:
    """
    Attributes:
        submitted (int): The number of groups submitted to all generation workers, only used
            for logging purposes (e.g. compute submitted / accepted ratio to see how many
            generations failed). This is strictly increasing.
        accepted (int): The number of groups finished generation that will be trained on (either
            already consumed by, or about to be consumed by the training worker). This is strictly
            increasing in the absence of filtering; ``on_rollout_filtered`` decrements it when an
            already-generated group is dropped from training (see ``sample_full_batch``).
        running (int): The number of groups currently being generated by the generation workers.
        filtered (int): The number of finished groups that were dropped from training (e.g.
            zero-variance groups under ``sample_full_batch``). This is strictly increasing. The
            invariant ``submitted == accepted + filtered + running`` always holds.
    """

    submitted: int = 0
    accepted: int = 0
    running: int = 0
    filtered: int = 0

class AsyncStalenessManager:
    """
    Bounds how far generation may run ahead of training, makes sure we don't generate
    rollouts that will end up being too old to use

    everything here is in groups (one group = one prompt). `groups_per_step` is
    "groups consumed per training step" -- that is trainer.batch_size, NOT
    mini_batch_size (the grad-accum chunk). Using the smaller number under-admits
    after the first step and deadlocks once K is exhausted.
    `max_concurrent_generation_groups` is the generation-worker count, and every
    `_RolloutStat` counter moves by 1 per group.
    `n_samples_per_prompt` is deliberately absent -- it never scales any of this.
    """

    def __init__(self, max_concurrent_generation_groups: int, groups_per_step: int, max_staleness_steps: int):
        self.max_concurrent_generation_groups = max_concurrent_generation_groups
        self.groups_per_step = groups_per_step
        self.max_staleness_steps = max_staleness_steps

        # Control logics.
        self._stat = _RolloutStat()
        self._cond = asyncio.Condition()

        # The current version that is being worked on, i.e. FullyAsyncRayPPOTrainer.global_step.
        # `self._current_global_step - 1` is the number of steps the model has finished training.
        self._current_global_step = 1

    def load_state_from_checkpoint(self, global_step: int) -> None:
        self._current_global_step = global_step
        self._stat.accepted = (global_step - 1) * self.groups_per_step
        self._stat.submitted = self._stat.accepted

    async def validate_state_at_epoch_end(self, global_step: int) -> None:
        """
        Check that the current version and accepted rollouts are consistent with the global step.

        Args:
            global_step: The global step we are about to train on (after incrementing).
        """
        async with self._cond:
            assert self._stat.running == 0, "We expect no rollouts are running at end of an epoch."
            consumed = (global_step - 1) * self.groups_per_step
            assert (
                self._stat.accepted == consumed
            ), f"Unexpected number of accepted rollouts. Got {self._stat.accepted} != {consumed}."
            assert (
                self._current_global_step == global_step
            ), f"Unexpected current version. Got {self._current_global_step} != {global_step}."
            # All submitted rollouts must have finished as either accepted (trained) or filtered (dropped).
            assert self._stat.submitted == self._stat.accepted + self._stat.filtered, (
                "We expect all submitted rollouts to be accepted or filtered at end of an epoch. "
                f"Got {self._stat.submitted} != {self._stat.accepted} + {self._stat.filtered}."
            )

    def _compute_capacity_unlocked(self) -> int:
        """How many more groups may be submitted right now. <= 0 means block.

        Everything below is in GROUPS. Two independent ceilings; obey the tighter one.
        """
        # Cumulative ceiling: total groups the trainer will ever have consumed by the time
        # it finishes the step it is allowed to run ahead to.
        #   max_staleness_steps [steps] x groups_per_step [groups/step] = groups
        # NOTE: no +1 needed -- _current_global_step is "the step being worked on", so it
        # already equals (steps finished + 1).
        consumer_capacity = (self.max_staleness_steps + self._current_global_step) * self.groups_per_step

        # Staleness headroom. Both `accepted` and `consumer_capacity` are LIFETIME totals
        # (accepted accumulates across epochs), so this is not a buffer occupancy -- it is
        # how much further production may run ahead of consumption before it is too stale.
        producer_staleness_capacity = consumer_capacity - (self._stat.accepted + self._stat.running)

        # Concurrency headroom: free generation-worker slots. Both terms are groups.
        producer_concurrency_capacity = self.max_concurrent_generation_groups - self._stat.running

        # Tighter of the two. These bind at different times: concurrency caps how many run
        # AT ONCE, staleness caps how far AHEAD OF THE TRAINER we may get.
        # May return negative (e.g. after a checkpoint resume rewinds _current_global_step
        # below work already admitted). Callers test `<= 0`, so negative just means block.
        return min(producer_concurrency_capacity, producer_staleness_capacity)

    async def acquire_submission_slot(self) -> None:
        """Block until there is capacity, then reserve a slot (increments submitted and running).

        This method always uses the latest current version tracked internally, which is
        updated by `notify_capacity_change(new_global_step)`.
        """
        async with self._cond:
            while self._compute_capacity_unlocked() <= 0: # is there space for more samples? can go negative if we restart at an earlier checkpoint
                await self._cond.wait()
            # Reserve slot
            self._stat.submitted += 1
            self._stat.running += 1

    async def on_rollout_accepted(self) -> None:
        # get_batch() just drained a trajectory that will be trained on.
        async with self._cond:
            self._stat.accepted += 1
            self._stat.running -= 1
            self._cond.notify_all()

    async def on_rollout_filtered(self) -> None:
        """Reclassify an already-accepted group as filtered when it is dropped from training.

        Without this, dropped groups keep counting toward ``accepted`` while ``current_global_step``
        only advances on trained steps, shrinking producer capacity on every drop -> deadlock.
        """
        async with self._cond:
            self._stat.accepted -= 1
            self._stat.filtered += 1
            self._cond.notify_all()

    async def on_rollout_rejected(self) -> None:
        """Generation failed, or a finished trajectory was dropped before training.

        Never counted as accepted, so this only frees the running slot. ``filtered``
        advances so ``submitted == accepted + filtered + running`` still holds.
        """
        async with self._cond:
            self._stat.running -= 1
            self._stat.filtered += 1
            self._cond.notify_all()

    async def notify_capacity_change(self, new_global_step: int) -> None:
        # Called when current_global_step changes (e.g., after a training step)
        async with self._cond:
            self._current_global_step = int(new_global_step)
            self._cond.notify_all()

class AsyncDataLoader:

    """
    Stateful Data Loader provided by pytorch is not reliable, it doesn't keep track of what the model has seen across runs reliably, 
    leading to training on the same data if we start at a certain checkpoint. We fix this by keep a list of consumed_ids and filtered_ids
    that help us keep track of what data we've trained on at each checkpoint
    """

    def __init__(self, train_dataloader: StatefulDataLoader, mini_batch_size: int):
        self._train_dataloader = train_dataloader
        self._train_dataloader_initial_state = train_dataloader.state_dict()
        
        # data loader has to be a multiple of mini_batch_size, we drop last
        self._effective_dataloader_length = len(self._train_dataloader) // mini_batch_size * mini_batch_size 

        self._iter = enumerate(self._train_dataloader) # next batch with the batch index in the dataset, resets every epoch
        self._lock = asyncio.Lock() # ensures no race conditions when multiple generators write to the consumed / filtered arrays

        self._consumed_data_uids: Set[str] = set()
        self._filtered_data_uids: Set[str] = set()
        self._exhausted: bool = False # not being used

    def load_state_from_checkpoint(self, consumed_data_uids_set: Set[str], filtered_data_uids_set: Optional[Set[str]] = None) -> None: 
        """
        Load state from checkpoint
        """
        self._consumed_data_uids = consumed_data_uids_set
        self._filtered_data_uids = filtered_data_uids_set if filtered_data_uids_set is not None else set()

        # Reset in case the dataloader loaded the state from the checkpoint, which we do not want.
        self._train_dataloader.load_state_dict(self._train_dataloader_initial_state)

    async def reset_at_epoch_end(self) -> None:
        async with self._lock:
            self._train_dataloader.load_state_dict(self._train_dataloader_initial_state)  # reset to initial state
            self._iter = enumerate(self._train_dataloader)
            self._consumed_data_uids.clear()
            self._filtered_data_uids.clear()
            self._exhausted = False

    async def get_next_non_consumed_data(self):
        """
        Return the next batch of training data.

        If we loaded from a checkpoint, it will skip the already-consumed data. Returns None if the dataloader is exhausted.
        """
        assert self._iter is not None and self._lock is not None, "Dataloader not initialized; call reset() first"
        async with self._lock:
            try:
                while True:
                    # Keep polling until we get a non-consumed data or the dataloader is exhausted.
                    iter_idx, rand_prompts = next(self._iter)
                    if iter_idx >= self._effective_dataloader_length: # we've gone over the amount of trainable batches in our dataset
                        raise StopIteration
                    uid = rand_prompts[0]["uid"]
                    if uid not in self._consumed_data_uids:
                        return rand_prompts
            except StopIteration:
                self._exhausted = True # no more training to be done
                return None

    async def mark_consumed_uids(self, uids: Iterable[str]) -> None:
        """Mark UIDs as trained on (and hence consumed)."""
        assert self._lock is not None, "Dataloader not initialized; call reset() first"
        async with self._lock:
            for uid in uids:
                assert uid not in self._consumed_data_uids, "Duplicate UID found in mini-batch"
                self._consumed_data_uids.add(uid)

    async def mark_filtered_uids(self, uids: Iterable[str]) -> None:
        """Mark UIDs as dropped (not trained on): added to the do-not-redraw set and recorded as
        filtered so they are skipped on resume and excluded from the trained-step count."""
        assert self._lock is not None, "Dataloader not initialized; call reset() first"
        async with self._lock:
            for uid in uids:
                assert uid not in self._consumed_data_uids, "Duplicate UID found in mini-batch"
                self._consumed_data_uids.add(uid)
                self._filtered_data_uids.add(uid)

    def get_consumed_uids_list(self) -> List[str]:
        return list(self._consumed_data_uids)

    def get_filtered_uids_list(self) -> List[str]:
        return list(self._filtered_data_uids)

    def num_trained(self) -> int:
        """Number of UIDs consumed by training (excludes filtered/dropped UIDs)."""
        return len(self._consumed_data_uids) - len(self._filtered_data_uids)

def build_dataloader(cfg: Config, dataset: Dataset, is_train: bool=True, is_fully_async:bool=False) -> StatefulDataLoader: 

    batch_size = cfg.trainer.batch_size if is_train else cfg.trainer.eval_batch_size

    seeded_generator = torch.Generator()
    seeded_generator.manual_seed(cfg.trainer.seed)

    num_workers = cfg.num_workers
    assert num_workers is not None, "dataloader must have num_workers > 0"

    dataloader = StatefulDataLoader(
        dataset,
        batch_size=batch_size if not is_fully_async else 1,
        shuffle=True if is_train else False,
        collate_fn=dataset.collate_fn, 
        num_workers=num_workers,
        drop_last=True if is_train else False,
        generator=seeded_generator,
    )
    if is_train:
        if not is_fully_async:
            logger.info(f"Total steps: {len(dataloader) * cfg.trainer.epochs}")
        else:
            logger.info(f"Total steps: {cfg.trainer.total_steps}")
    else:
        logger.info(f"Validation set size: {len(dataloader)}")
    return dataloader

@dataclass
class TrainerState:
    """Everything that must survive a checkpoint/resume."""

    step: int = 0
    policy_version: int = 0
    clipper: EMAAdvantageClipper = field(default_factory=EMAAdvantageClipper)

    def state_dict(self) -> dict:
        return {
            "step": self.step,
            "policy_version": self.policy_version,
            "clipper": self.clipper.state_dict(),
        }

    def load_state_dict(self, state: dict) -> None:
        self.step = state["step"]
        self.policy_version = state["policy_version"]
        self.clipper.load_state_dict(state["clipper"])

class SDPOTrainer:
    """
    Off-policy SDPO trainer
    """

    def __init__(
        self,
        model,
        tokenizer,
        config: Config,
        tasks_by_id: dict[str, Task],
        optimizer: torch.optim.Optimizer | None = None,
        device: torch.device | str = "cuda",
        transport: WeightTransport | None = None,
    ) -> None:
        # No store here on purpose. The store is PRODUCER state -- it belongs to the
        # rollout side in run.py, which owns it on rank 0 and hands each rank its batch.
        # The trainer is model + optimizer only, so every rank constructs an identical one
        # and train_step() is a pure function of the trajectories it is given.
        self.model = model
        self.tokenizer = tokenizer
        self.config = config
        self.tasks_by_id = tasks_by_id
        self.device = device
        # Full activations at mini-batch x ~3.5k tokens exceed 80 GB; checkpointing trades
        # them for recompute
        if config.trainer.gradient_checkpointing:
            self.unwrapped.gradient_checkpointing_enable(
                gradient_checkpointing_kwargs={"use_reentrant": False}
            )
            self.unwrapped.config.use_cache = False
        else:
            self.unwrapped.config.use_cache = True

        self.state = TrainerState(
            clipper=EMAAdvantageClipper(
                mult=config.trainer.algorithm.adv_clip_mult,
                decay=config.trainer.algorithm.adv_ema_decay,
                bias_correction=config.trainer.algorithm.adv_ema_bias_correction,
            )
        )
        self.staleness_manager = AsyncStalenessManager(
            # Running includes both in-flight generations and trajectories sitting in the
            # store until get_batch() accepts them, so this ceiling must be the store
            # size -- hint.concurrency only bounds the hint LLM, not generation slots.
            max_concurrent_generation_groups=config.generator.engine.store_capacity,
            # get_batch() drains trainer.batch_size trajectories per step. Passing
            # mini_batch_size (grad-accum chunk) here under-admits after step 1 and
            # deadlocks at K: the producer can only refill K * mini extra groups.
            groups_per_step=config.trainer.batch_size,
            max_staleness_steps=config.trainer.algorithm.max_staleness,
        )
        self.optimizer = optimizer or torch.optim.AdamW(
            model.parameters(),
            lr=config.trainer.optimizer.learning_rate,
            weight_decay=config.trainer.optimizer.weight_decay,
        )
        # The send side of weight sync (WeightTransport). None on DDP ranks
        # 1..N-1 and in tests -- only rank 0 pushes weights to the rollout engines.
        self.transport = transport
        # Flipped by setup_weight_sync(); guards against sending before the rendezvous.
        self._weight_sync_ready = False
        # The FSDP2 root, resolved through the torch.compile wrapper: a compiled model is
        # an OptimizedModule, so an isinstance check on self.model would miss it. FSDP2
        # mutates the module in place rather than wrapping it, so this checks the
        # unwrapped model against FSDPModule. None when single-GPU or under test.
        inner = getattr(model, "_orig_mod", model)
        self._fsdp = inner if isinstance(inner, FSDPModule) else None

    @property
    def unwrapped(self):
        """
        The bare HF model beneath the wrappers. torch.compile prefixes parameter names
        with `_orig_mod.` vLLM's weight receiver and checkpoints need the real HF names,
        so anything that reads names or state dicts must go through here.

        Unlike DDP, FSDP2 mutates the module in place instead of wrapping it, so there is
        no `module.` level to peel: the compile wrapper is the only one left.
        """
        return getattr(self.model, "_orig_mod", self.model)

    # ---- forward passes ----
    def _response_logprobs(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        response_mask: torch.Tensor,
        max_response: int,
    ) -> torch.Tensor:
        # FSDP shards live on these submodules (per-layer fully_shard + root).
        backbone = self.unwrapped.model
        hidden = backbone(
            input_ids=input_ids,
            attention_mask=attention_mask,
            use_cache=False,
        ).last_hidden_state
        return response_logprobs_from_hidden(
            hidden,
            self.unwrapped.lm_head,
            input_ids,
            response_mask,
            max_response,
        )

    def _student_logprobs(self, batch: SDPOBatch, max_response: int) -> torch.Tensor:
        return self._response_logprobs(
            batch.student_input_ids,
            batch.student_attention_mask,
            batch.student_response_mask,
            max_response,
        )

    def _hint_suffix_ids(self, hint: str) -> list[int]:
        if not hint:
            return []
        return self.tokenizer(
            f"{HINT_SEPARATOR}{hint}", add_special_tokens=False
        )["input_ids"]

    def _teacher_prompt_ids(self, trajectory, hint: str) -> list[int]:
        """Reuse the rollout's prompt ids and append a separately tokenized hint.

        Retokenizing `prompt + hint` as one string can merge tokens at the boundary and
        diverge from vLLM's `prompt_token_ids`.
        """
        return list(trajectory.prompt_token_ids) + self._hint_suffix_ids(hint)

    @torch.inference_mode()
    def _teacher_logprobs(
        self, batch: SDPOBatch, max_response: int
    ) -> tuple[torch.Tensor, torch.Tensor | None, torch.Tensor | None]:
        """Teacher log-probs under eval + inference_mode.

        Returns `(loss_teacher, lp_free, lp_bearing)`. Single-arm: extras are None.
        Mixture: `loss_teacher = 0.5 * (lp_free + lp_bearing)` from one stacked forward.
        """
        was_training = self.model.training
        self.model.eval()
        try:
            if batch.teacher_bearing_input_ids is None:
                lp = self._response_logprobs(
                    batch.teacher_input_ids,
                    batch.teacher_attention_mask,
                    batch.teacher_response_mask,
                    max_response,
                )
                return lp, None, None

            pad_id = self.tokenizer.pad_token_id
            if pad_id is None:
                pad_id = self.tokenizer.eos_token_id
            ids, attn, resp = _stack_teacher_sequences(batch, pad_id)
            lp_all = self._response_logprobs(ids, attn, resp, max_response)
            n = batch.teacher_input_ids.size(0)
            lp_free, lp_bearing = lp_all[:n], lp_all[n:]
            return 0.5 * (lp_free + lp_bearing), lp_free, lp_bearing
        finally:
            if was_training:
                self.model.train()

    def prepare_batch(self, trajectories):
        """Assemble padded tensors. Teacher prompt ids = rollout prompt + tokenized hint.

        Hints are read from the trajectory, not from current config, so a mid-run hint
        change can't mix two different teachers into one batch. Mixture attaches a second
        (answer-bearing) teacher sequence on the batch.
        """
        pad_id = self.tokenizer.pad_token_id
        if pad_id is None:
            pad_id = self.tokenizer.eos_token_id
        mode = self.config.generator.hint.prompt

        if mode == "answer_bearing":
            teacher_ids = [
                self._teacher_prompt_ids(t, t.hint_bearing) for t in trajectories
            ]
        else:
            teacher_ids = [
                self._teacher_prompt_ids(t, t.hint_free) for t in trajectories
            ]
        batch = build_batch(trajectories, teacher_ids, pad_token_id=pad_id)

        if mode == "mixture":
            bearing_ids = [
                self._teacher_prompt_ids(t, t.hint_bearing) for t in trajectories
            ]
            bearing_batch = build_batch(trajectories, bearing_ids, pad_token_id=pad_id)
            batch.teacher_bearing_input_ids = bearing_batch.teacher_input_ids
            batch.teacher_bearing_attention_mask = bearing_batch.teacher_attention_mask
            batch.teacher_bearing_response_mask = bearing_batch.teacher_response_mask

        return batch

    def train_step(self, trajectories) -> dict[str, float]:
        """One optimizer step over a batch, run in mini-batches for memory."""
        if not trajectories:
            return {}

        self.model.train()
        batch = self.prepare_batch(trajectories).to(self.device)
        max_response = batch.response_mask.size(1)

        self.optimizer.zero_grad(set_to_none=True)
        accumulated: dict[str, float] = defaultdict(float)
        n_micro = 0

        # Chunk this rank's batch into minibatches - they'll be processed sequentially
        starts = list(range(0, len(trajectories), self.config.trainer.mini_batch_size))

        for start in starts:
            end = min(start + self.config.trainer.mini_batch_size, len(trajectories))
            micro = _slice_batch(batch, start, end)

            # NOTE: deliberately no no_sync()/set_requires_gradient_sync() here, every
            # micro-batch reduce-scatters its gradients.
            student_lp = self._student_logprobs(micro, max_response)
            teacher_lp, lp_free, lp_bearing = self._teacher_logprobs(micro, max_response)

            loss, metrics = sdpo_loss(
                student_log_probs=student_lp,
                teacher_log_probs=teacher_lp,
                rollout_log_probs=micro.rollout_logprobs,
                response_mask=micro.response_mask,
                clipper=self.state.clipper,
                clip_low=self.config.trainer.algorithm.clip_ratio_low,
                clip_high=self.config.trainer.algorithm.clip_ratio_high,
                one_sided=self.config.trainer.algorithm.use_one_sided_clip,
                one_sided_max=self.config.trainer.algorithm.one_sided_clip_max,
                step_ids=micro.step_ids,
                use_sod=self.config.trainer.algorithm.use_sod,
                sod_eps=self.config.trainer.algorithm.sod_eps,
                sod_delta=self.config.trainer.algorithm.sod_delta,
            )
            if lp_free is not None and lp_bearing is not None:
                metrics["teacher_free_minus_student_logp"] = masked_mean(
                    (lp_free - student_lp).detach(), micro.response_mask
                ).item()
                metrics["teacher_bearing_minus_student_logp"] = masked_mean(
                    (lp_bearing - student_lp).detach(), micro.response_mask
                ).item()

            # Scale so the summed gradient equals the full-batch mean. Still correct with
            # per-chunk sync: reduce-scatter sums across ranks and each rank accumulates
            # into its own shard, so the arithmetic is unchanged.
            (loss / len(starts)).backward()

            for key, value in metrics.items():
                accumulated[key] += value
            
            # number of microbatches processed
            n_micro += 1

        grad_norm = torch.nn.utils.clip_grad_norm_(
            self.model.parameters(), self.config.trainer.optimizer.max_grad_norm
        )
        self.optimizer.step()
        self.state.step += 1
        

        # The EMA must agree across ranks or they clip differently and slowly diverge.
        self._sync_clipper()

        averaged = {k: v / max(n_micro, 1) for k, v in accumulated.items()} # average stats across all microbatches
        averaged["grad_norm"] = float(grad_norm)
        averaged["step"] = float(self.state.step)
        averaged["mean_batch_staleness"] = float(
            (self.state.policy_version - batch.policy_versions.float()).mean() # tracks staleness average by comparing our trainer state's policy version (updated through weight syncs) and each labelled sample's policy
        )
        return averaged

    def _sync_clipper(self) -> None:
        """All-reduce the advantage EMA so every trainer rank clips identically."""
        if not (dist.is_available() and dist.is_initialized()):
            return
        tensor = torch.tensor([self.state.clipper.ema], device=self.device)
        dist.all_reduce(tensor, op=dist.ReduceOp.AVG)
        self.state.clipper.sync_(float(tensor.item()))

    # ---- weight sync (vLLM native NCCL transfer) ----

    def setup_weight_sync(self, master_address: str, master_port: int, world_size: int) -> None:
        """Join the weight-transfer group as the SENDER at rank 0, via the transport.

        `world_size` counts rollout GPU workers plus one for the trainer -- each rollout
        engine contributes `tensor_parallel_size` ranks, not one rank per engine. This
        blocks until every rank has joined, so the rollout engines must already be
        initializing their side (the orchestrator issues both concurrently).
        """
        if self.transport is None:
            raise RuntimeError(
                "no weight transport; construct SDPOTrainer with transport=... to sync weights"
            )
        # asyncio.to_thread does not inherit this process's CUDA device; NCCL then
        # binds the sender to cuda:0, which is a vLLM worker ("Duplicate GPU").
        if isinstance(self.device, torch.device) and self.device.type == "cuda":
            torch.cuda.set_device(self.device)
        self.transport.setup(master_address, master_port, world_size)
        self._weight_sync_ready = True

    def weight_buckets(self):
        
        max_bytes = self.config.generator.engine.weight_sync_bucket_mb * 1024 * 1024
        bucket: list[tuple[str, torch.Tensor]] = []
        bucket_bytes = 0

        for name, param in self.unwrapped.named_parameters():
            tensor = param.data

            # DTensor is a tensor with metadata being 1024x1024, but the actual tensor in memory is 256x1024 for example
            # DTensor also holds metadata like which GPU the tensor belongs to, so Mesh can track it when colocation is necessary
            # DTensor allows broadcasting to be easier, easier to colocate the full weight tensor aftre the fact
            if isinstance(tensor, DTensor):
                tensor = tensor.full_tensor()
            bucket.append((name, tensor))
            # Size by the FULL tensor, not this rank's shard, or buckets would be N times too large on an N-rank mesh.
            bucket_bytes += tensor.numel() * tensor.element_size()
            if bucket_bytes >= max_bytes:
                yield _pack_bucket(bucket)
                bucket, bucket_bytes = [], 0
        if bucket:
            yield _pack_bucket(bucket)

    def send_weight_bucket(self, bucket: WeightBucket) -> None:
        """Broadcast one bucket through the transport.

        The receivers post their matching broadcasts from the metadata in their update
        request, so send order must match `bucket.names` exactly. Their RPC must already be
        in flight when this is called, or this blocks on a broadcast nobody is listening
        for -- the orchestrator owns that interleaving.
        """
        if not self._weight_sync_ready:
            raise RuntimeError("weight sync not initialized; call setup_weight_sync first")
        if isinstance(self.device, torch.device) and self.device.type == "cuda":
            torch.cuda.set_device(self.device)
        self.transport.send_bucket(bucket)

    def bump_policy_version(self) -> int:
        """Advance the policy version after pushing weights to the rollout engines.

        Called by the orchestrator AFTER the weight push completes. Trajectories already in
        the store get one step staler; anything past K=3 is evicted on the next sample.
        """
        self.state.policy_version += 1
        return self.state.policy_version

    # ---- checkpointing ----

    def state_dict(self) -> dict:
        """Full (unsharded) model + optimizer state.

        Under FSDP2 both the parameters and the optimizer state are sharded, so a plain
        state_dict() would write this rank's fragments. `get_state_dict` with
        full_state_dict=True gathers the shards; cpu_offload=True assembles into host RAM
        so we do not need a spare model-sized block of VRAM to hold the result.

        This is a COLLECTIVE -- every rank must call it, though only rank 0 receives the
        populated dict and writes the file. run.py's save_checkpoint broadcasts a
        "checkpoint" command so the workers join.
        """
        if self._fsdp is None:
            return {
                "model": self.unwrapped.state_dict(),
                "optimizer": self.optimizer.state_dict(),
                "trainer": self.state.state_dict(),
            }

        model_state, optimizer_state = get_state_dict(
            self.unwrapped,
            self.optimizer,
            options=StateDictOptions(full_state_dict=True, cpu_offload=True),
        )
        return {
            "model": model_state,
            "optimizer": optimizer_state,
            "trainer": self.state.state_dict(),
        }

    def load_state_dict(self, state: dict) -> None:
        """Load a full state dict, resharding it across ranks under FSDP2."""
        if self._fsdp is None:
            self.unwrapped.load_state_dict(state["model"])
            self.optimizer.load_state_dict(state["optimizer"])
        else:
            set_state_dict(
                self.unwrapped,
                self.optimizer,
                model_state_dict=state["model"],
                optim_state_dict=state["optimizer"],
                options=StateDictOptions(full_state_dict=True, cpu_offload=True),
            )
        self.state.load_state_dict(state["trainer"])


def _pack_bucket(bucket: list[tuple[str, torch.Tensor]]) -> WeightBucket:
    """Cast one bucket to bf16 and extract the metadata the receivers need."""
    names, tensors = [], []
    for name, param in bucket:
        tensor = param.data
        if tensor.dtype != torch.bfloat16:
            tensor = tensor.to(torch.bfloat16)
        names.append(name)
        tensors.append(tensor)
    dtype_names = [str(t.dtype).split(".")[-1] for t in tensors]
    shapes = [list(t.shape) for t in tensors]
    return WeightBucket(
        names=names, dtype_names=dtype_names, shapes=shapes, tensors=tensors
    )


def _pad_seq(tensor: torch.Tensor, length: int, value: int | float) -> torch.Tensor:
    if tensor.size(1) >= length:
        return tensor
    pad = tensor.new_full((tensor.size(0), length - tensor.size(1)), value)
    return torch.cat([tensor, pad], dim=1)


def _stack_teacher_sequences(batch: SDPOBatch, pad_id: int) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Cat free then bearing teachers along the batch dim, padding seq length."""
    assert batch.teacher_bearing_input_ids is not None
    assert batch.teacher_bearing_attention_mask is not None
    assert batch.teacher_bearing_response_mask is not None
    length = max(batch.teacher_input_ids.size(1), batch.teacher_bearing_input_ids.size(1))
    ids = torch.cat(
        [
            _pad_seq(batch.teacher_input_ids, length, pad_id),
            _pad_seq(batch.teacher_bearing_input_ids, length, pad_id),
        ],
        dim=0,
    )
    attn = torch.cat(
        [
            _pad_seq(batch.teacher_attention_mask, length, 0),
            _pad_seq(batch.teacher_bearing_attention_mask, length, 0),
        ],
        dim=0,
    )
    resp = torch.cat(
        [
            _pad_seq(batch.teacher_response_mask, length, 0),
            _pad_seq(batch.teacher_bearing_response_mask, length, 0),
        ],
        dim=0,
    )
    return ids, attn, resp


def _slice_batch(batch: SDPOBatch, start: int, end: int) -> SDPOBatch:
    """Slice a batch along the batch dimension for gradient accumulation."""
    def _slice(t: torch.Tensor | None) -> torch.Tensor | None:
        return None if t is None else t[start:end]

    return SDPOBatch(
        student_input_ids=batch.student_input_ids[start:end],
        student_attention_mask=batch.student_attention_mask[start:end],
        student_response_mask=batch.student_response_mask[start:end],
        teacher_input_ids=batch.teacher_input_ids[start:end],
        teacher_attention_mask=batch.teacher_attention_mask[start:end],
        teacher_response_mask=batch.teacher_response_mask[start:end],
        rollout_logprobs=batch.rollout_logprobs[start:end],
        response_mask=batch.response_mask[start:end],
        task_ids=batch.task_ids[start:end],
        policy_versions=batch.policy_versions[start:end],
        step_ids=_slice(batch.step_ids),
        teacher_bearing_input_ids=_slice(batch.teacher_bearing_input_ids),
        teacher_bearing_attention_mask=_slice(batch.teacher_bearing_attention_mask),
        teacher_bearing_response_mask=_slice(batch.teacher_bearing_response_mask),
    )


def log_metrics(metrics: dict[str, float], store: TrajectoryStore) -> None:
    """Emit one line per step, leading with the diagnostics that actually matter."""
    combined = {**metrics, **store.metrics()}
    gap = combined.get("teacher_minus_student_logp", 0.0)
    logger.info(
        "step %d | loss %.4f | teacher-student gap %+.4f | adv_clip %.1f%% | "
        "ratio_clip lo %.1f%% hi %.1f%% | staleness %.2f | grad %.3f",
        int(combined.get("step", 0)),
        combined.get("loss", 0.0),
        gap,
        100 * combined.get("adv_clip_frac", 0.0),
        100 * combined.get("ratio_clip_frac_low", 0.0),
        100 * combined.get("ratio_clip_frac_high", 0.0),
        combined.get("store_mean_staleness", 0.0),
        combined.get("grad_norm", 0.0),
    )
    if abs(gap) < 1e-3:
        logger.warning(
            "teacher-student gap is ~0 (%.6f): the hint is not making the teacher better "
            "than the student, so the SDPO gradient has vanished and training will not "
            "move. Try generator.hint.prompt='answer_bearing' for a stronger teacher "
            "(see data/prompts/).",
            gap,
        )
